disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: ''

menu:
- {name: 'About', path: '.', url: 'index.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Teaching', path: 'menu', url: 'teaching.html'}
- {name: 'Industry', path: 'menu', url: 'industry.html'}
- {name: 'Education', path: 'menu', url: 'education.html'}
- {name: 'Honors', path: 'menu', url: 'honors.html'}

social:
- {icon: 'github', link: 'https://www.github.com/artem-timoshenko'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0002-5431-2136'}
- {icon: 'envelope', link: 'mailto:artem.timoshenko@kellogg.northwestern.edu'}
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=ebyna6wAAAAJ'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'
sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy:'
post_date_prefix: 'Written on'
